/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description 由谁创建或修改 */
    NCreateEditBy: {
      /** @enum {string} */
      type: "user";
      id: string;
    };
    /** @description 封面图 */
    NCover: {
      /** @enum {string} */
      type: "external";
      external: Record<string, never>;
    };
    /** @description 图标 */
    NIcon: {
      /** @enum {string} */
      type: "emoji";
      emoji: string;
    };
    NParent: {
      /**
       * @description 这里只列举了目前已知值
       * @enum {string}
       */
      type: "workspace" | "page_id" | "database_id";
      workspace?: boolean;
      database_id?: string;
      /** @description 如果 parent 是 page，那么这里就是 page 的 id */
      page_id?: string;
    };
    /** @description 属性（即每个表格的每一列信息） */
    NProperty: {
      id: string;
      /**
       * @description 表示这一列是文本、日期、多选等
       * @enum {string}
       */
      type: "checkbox" | "created_by" | "created_time" | "date" | "email" | "files" | "formula" | "last_edited_by" | "last_edited_time" | "multi_select" | "number" | "people" | "phone_number" | "relation" | "rich_text" | "rollup" | "select" | "status" | "title" | "url";
      /** @description 这一列展示出来的列名 */
      name: string;
      formula?: {
        expression?: string;
      };
      multi_select?: ({
          /** @enum {string} */
          color?: "blue" | "brown" | "default" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | "yellow";
          id?: string;
          name?: string;
        })[];
      number?: {
        /** @enum {string} */
        format?: "argentine_peso" | "baht" | "australian_dollar" | "canadian_dollar" | "chilean_peso" | "colombian_peso" | "danish_krone" | "dirham" | "dollar" | "euro" | "forint" | "franc" | "hong_kong_dollar" | "koruna" | "krona" | "leu" | "lira" | "mexican_peso" | "new_taiwan_dollar" | "new_zealand_dollar" | "norwegian_krone" | "number" | "number_with_commas" | "percent" | "philippine_peso" | "pound" | "peruvian_sol" | "rand" | "real" | "ringgit" | "riyal" | "ruble" | "rupee" | "rupiah" | "shekel" | "singapore_dollar" | "uruguayan_peso" | "yen" | "yuan" | "won" | "zloty";
      };
      relation?: {
        database_id?: string;
        synced_property_id?: string;
        synced_property_name?: string;
      };
      rollup?: {
        /** @enum {string} */
        function?: "average" | "checked" | "count_per_group" | "count" | "count_values" | "date_range" | "earliest_date" | "empty" | "latest_date" | "max" | "median" | "min" | "not_empty" | "percent_checked" | "percent_empty" | "percent_not_empty" | "percent_per_group" | "percent_unchecked" | "range" | "unchecked" | "unique" | "show_original" | "show_unique" | "sum";
        relation_property_id?: string;
        relation_property_name?: string;
        rollup_property_id?: string;
        rollup_property_name?: string;
      };
      select?: {
        /** @enum {string} */
        color?: "blue" | "brown" | "default" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | "yellow";
        id?: string;
        name?: string;
      };
      status?: {
        options?: ({
            /** @enum {string} */
            color?: "blue" | "brown" | "default" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | "yellow";
            id?: string;
            /** @description Commas (",") are not valid for status values. */
            name?: string;
          })[];
        groups?: ({
            /** @enum {string} */
            color?: "blue" | "brown" | "default" | "gray" | "green" | "orange" | "pink" | "purple" | "red" | "yellow";
            id?: string;
            /** @description Commas (",") are not valid for status values. */
            name?: string;
            option_ids?: string[];
          })[];
      };
    };
    /** @description 文本样式注解。目前已知的应用场景是 Page 或 Database 的 title 的样式 */
    NAnnotations: {
      bold: boolean;
      italic: boolean;
      strikethrough: boolean;
      underline: boolean;
      code: boolean;
      /** @enum {string} */
      color: "blue" | "blue_background" | "brown" | "brown_background" | "default" | "gray" | "gray_background" | "green" | "green_background" | "orange" | "orange_background" | "pink" | "pink_background" | "purple" | "purple_background" | "red" | "red_background" | "yellow" | "yellow_background";
    };
    /** @description one of the three types of rich text */
    NTextLink: {
      content?: string;
      /** @description inline link */
      link?: string | null;
    };
    /** @description one of the three types of rich text */
    NMention: {
      /** @enum {string} */
      type?: "database" | "date" | "link_preview" | "page" | "template_mention" | "user";
      database?: {
        id?: string;
      };
      data?: {
        start?: string;
        end?: string | null;
      };
      link_preview?: {
        url?: string;
      };
      page?: {
        id?: string;
      };
      template_mention?: {
        /** @enum {string} */
        type?: "template_mention_date" | "template_mention_user";
        /** @enum {string} */
        template_mention_date?: "today" | "now";
        /** @enum {string} */
        template_mention_user?: "me";
      };
      user?: {
        id?: string;
        /** @enum {string} */
        object?: "user";
      };
    };
    /** @description one of the three types of rich text */
    NEquation: {
      expression: string;
    };
    /** @description Page 或 Database 的 title 也是 RichText */
    NRichText: {
      annotations: components["schemas"]["NAnnotations"];
      href?: string | null;
      plain_text: string;
      text?: components["schemas"]["NTextLink"];
      mention?: components["schemas"]["NMention"];
      equation?: components["schemas"]["NEquation"];
      /** @enum {string} */
      type: "text" | "mention" | "equation";
    };
    /** @description 一个 page 或 database 的 schema 信息。所有字段的格式都与 Notion API 的返回值保持一致。只有 workspaceId 这个字段是额外添加的，默认情况下， notion api 返回的数据是没有 workspaceId 的 字段 */
    NPDInfo: {
      /** @description page 或 database 的 id */
      id: string;
      workspaceId?: string;
      /** @enum {string} */
      object: "page" | "database";
      created_time: string;
      last_edited_time: string;
      created_by: components["schemas"]["NCreateEditBy"];
      last_edited_by: components["schemas"]["NCreateEditBy"];
      cover?: components["schemas"]["NCover"];
      icon?: components["schemas"]["NIcon"];
      parent: components["schemas"]["NParent"];
      archived: boolean;
      in_trash: boolean;
      /** @description 一个 dict，key 是展示出来的列名（即 Property.name），value 是 Property */
      properties: {
        [key: string]: components["schemas"]["NProperty"];
      };
      /** @description 内容尚不详 */
      description: Record<string, never>[];
      /** @description 应该是只有 database 才有 */
      is_inline: boolean;
      public_url?: string | null;
      /** @description database 的 title。尚不清楚为何返回的是一个 list */
      title: components["schemas"]["NRichText"][];
      url?: string | null;
    };
    NUser: {
      /** @enum {string} */
      object?: "user";
      id?: string;
      /** @enum {string} */
      type?: "person";
      person?: {
        email?: string;
      };
      name?: string;
      avatar_url?: string;
    };
    /** @description NAccessToken 中 owner 字段两个值之一 */
    NAccessTokenOwnerUser: {
      /** @enum {string} */
      type?: "user";
      user?: {
        id?: string;
        /** @enum {string} */
        object?: "user";
      };
    };
    /** @description NAccessToken 中 owner 字段两个值之一 */
    NAccessTokenOwnerWorkspace: {
      /** @enum {boolean} */
      workspace: true;
    };
    /** @description Notion API 获取 access token 接口的返回值 */
    NAccessToken: {
      access_token: string;
      bot_id: string;
      workspace_id: string;
      token_type: string;
      workspace_name?: string;
      workspace_icon?: string;
      /** @description 如果用户选择使用开发者提供的模板，那么该字段会是用户使用该模板创建的 page/database 的 id */
      duplicated_template_id?: string;
      request_id: string;
      owner: components["schemas"]["NAccessTokenOwnerUser"] | components["schemas"]["NAccessTokenOwnerWorkspace"];
    };
    /**
     * @description 是书、会议论文、期刊论文、还是别的类型。主要内容来自 crossref.org 的论文类型，https://api.crossref.org/v1/types。
     * @enum {string}
     */
    WorkType: "book-section" | "monograph" | "report-component" | "report" | "peer-review" | "book-track" | "journal-article" | "book-part" | "other" | "book" | "journal-volume" | "book-set" | "reference-entry" | "proceedings-article" | "journal" | "component" | "book-chapter" | "proceedings-series" | "report-series" | "proceedings" | "database" | "standard" | "reference-book" | "posted-content" | "journal-issue" | "dissertation" | "grant" | "dataset" | "book-series" | "edited-book";
    /** @description 内容主要来自 crossref.org 的 DOI 数据。出版日期取自其 issued 字段 */
    PublishInfo: {
      publisher?: string;
      containerTitle?: string;
      issue?: string;
      volume?: string;
      pages?: string;
      year?: string;
      month?: string;
      day?: string;
    };
    Author: {
      familyName?: string;
      givenName?: string;
      fullName?: string;
      /** @description Researcher's ID, can be found at https://orcid.org */
      ORCID?: string;
    };
    /** @description 原始内容下载链接 */
    DigitalResource: {
      /**
       * Format: uri
       * @description 原始内容的下载链接
       */
      resourceLink?: string;
      /** @description 原始内容的 mime 类型 */
      contentType?: string;
    };
    ClinicalTrial: {
      /** @description 临床试验的 id 号 */
      id?: string;
      /** @description 临床试验的注册机构的 DOI */
      registry?: string;
    };
    /**
     * @description 从哪个平台获取到的文献。不是该文献的来源，而是从哪个平台获取到的
     * @enum {string}
     */
    Platform: "arXiv" | "GoogleScholar";
    Work: {
      title?: string;
      /** @description 副标题 */
      subtitle?: string;
      authors?: components["schemas"]["Author"][];
      abstract?: string;
      /** @description 论文核心亮点。部分论文有 */
      highlights?: string[];
      /** @description 所属领域。对应 arxiv 的 category 字段 */
      subjects?: string[];
      DOI?: string;
      platform?: components["schemas"]["Platform"];
      platformId?: string;
      /**
       * Format: uri
       * @description 详情页链接
       */
      url?: string;
      /** @description 作者添加的注释，一般包含的内容：论文有多少页；相关数据可以在哪下载；等等 */
      authorComments?: string[];
      publishInfo?: components["schemas"]["PublishInfo"];
      /** @description 被引用次数 */
      referencedByCount?: number;
      type?: components["schemas"]["WorkType"];
      ISBN?: string[];
      digitalResources?: components["schemas"]["DigitalResource"][];
      clinicalTrial?: components["schemas"]["ClinicalTrial"][];
      /** @description 参考文献 */
      references?: components["schemas"]["Work"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
